version: 2.1

jobs:
  test-build:
    docker:
      - image: python:3.7.3-stretch

    steps:
      - checkout
      # run build
      - run:
          name: install dependencies
          command: |
            python3 -m venv .devops
            source .devops/bin/activate
            make install
      # run lint
      - run:
          name: run lint
          command: |
            source .devops/bin/activate
            make lint

  upload-docker:
      docker:
        - image: cimg/go:1.17
      steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.14
            docker_layer_caching: true
        - run:
            name: Build docker container
            command: |
              docker build --tag=hello-image .
              docker image ls
        - run:
            name: Upload Docker to Dockerhub
            command: |
              TAG="0.1.${CIRCLE_BUILD_NUM}" | tr '[:upper:]' '[:lower:]'
              DOCKERPATH="mo9348/hello-app"
              docker login --username=mo9348 --password=$DOCKERHUB_PASSWORD
              docker tag "hello-app:latest" "${DOCKERPATH}:${TAG}"  
              docker push "${DOCKERPATH}"

workflows:
  default:
    jobs:
      - test-build
      - upload-docker:
          requires: [test-build]