version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
  aws-cli: circleci/aws-cli@3.1.1

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws delete cluster --stack-name --region=us-east-2 "eksctl-${CIRCLE_WORKFLOW_ID:0:7}"

jobs:
  test-build:
    docker:
      - image: python:3.7.3-stretch

    steps:
      - checkout
      # run build
      - run:
          name: install dependencies
          command: |
            python3 -m venv .devops
            source .devops/bin/activate
            make install
      # run lint
      - run:
          name: run lint
          command: |
            source .devops/bin/activate
            make lint

  upload-docker:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build docker container
          command: |
            docker build --tag=hello-image .
            docker image ls
      - run:
          name: Upload Docker to Dockerhub
          command: |
            dockerpath="mo9348/hello-image"
            docker login --username=mo9348 --password=$DOCKERHUB_PASSWORD
            docker tag "hello-image:latest" $dockerpath
            docker push $dockerpath

  deploy:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: pull image
          command: |
            docker --version
            docker login --username=mo9348 --password=$DOCKERHUB_PASSWORD
            docker pull mo9348/hello-image
            docker images
      - run:
          name: Install dependancies
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Create an EKS Cluster
          command: |
            kubectl create namespace "hello-app"
            kubectl apply -f deploy.yml
            kubectl apply -f service.yaml
            kubectl get all -n "hello-app"


workflows:
  default:
    jobs:
      - test-build
      - upload-docker:
          requires: [test-build]
      - deploy:
          requires: [upload-docker]
          
