version: 2.1

jobs:
  test-build:
    docker:
      - image: python:3.7.3-stretch

    steps:
      - checkout
      # run build
      - run:
          name: install dependencies
          command: |
            python3 -m venv .devops
            source .devops/bin/activate
            ls
            pwd
            make install
      # run lint
      - run:
          name: run lint
          command: |
            source .devops/bin/activate
            make lint

  upload-docker:
      docker:
        - image: cimg/base:2021.11
          auth:
            username: Mo9348
            password: $DOCKERHUB_PASSWORD
      steps:
        - checkout
        - run:
            name: "echo an env var that is part of our project"
            command: |
              echo $MY_ENV_VAR # this env var must be set within the project

workflows:
  default:
    jobs:
      - test-build
      - upload-docker:
          requires: [test-build]