version: 2.1

orbs: 
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

jobs:
  test-build:
    docker:
      - image: python:3.7.3-stretch

    steps:
      - checkout
      # run build
      - run:
          name: install dependencies
          command: |
            python3 -m venv .devops
            source .devops/bin/activate
            make install
      # run lint
      - run:
          name: run lint
          command: |
            source .devops/bin/activate
            make lint

  upload-docker:
      docker:
        - image: cimg/go:1.17
      steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.14
        - run:
            name: Build docker container
            command: |
              docker build --tag=hello-image .
              docker image ls
        - run:
            name: Upload Docker to Dockerhub
            command: |
              TAG="0.1.${CIRCLE_BUILD_NUM}" | tr '[:upper:]' '[:lower:]'
              dockerpath="mo9348/hello-image"
              docker login --username=mo9348 --password=$DOCKERHUB_PASSWORD
              docker tag "hello-image:latest" $dockerpath
              docker push $dockerpath

  deploy:
      docker:
        - image: cimg/python:3.10
      steps:
        - checkout
        - kubernetes/install:
            kubectl-version: v1.22.0
        - run:
            name: Create an EKS Cluster
            command: |
              eksctl create cluster --name eksctl-hello-app --region=us-east-2
              eksctl utils describe-stacks --region=us-east-2 --cluster=eksctl-hello-app
              eksctl get cluster --name=eksctl-demo --region=us-east-2
        - run:
            name: Deploy
            command: |
              kubectl create deploy python-helloworld --image=mo9348/hello-image:latest
              kubectl get deploy,rs,svc,pods

workflows:
  default:
    jobs:
      - test-build
      - upload-docker:
          requires: [test-build]
      - deploy:
          requires: [upload-docker]